enableGlobalCache: true
nodeLinker: node-modules

packageExtensions:
  "@sapphire/decorators@*":
    dependencies:
      "@sapphire/discord.js-utilities": "*"
      "@sapphire/framework": "*"
      discord.js: "^13.8.1"
  "@sapphire/discord.js-utilities@*":
    dependencies:
      discord-api-types: "*"
      discord.js: "^13.8.1"
  "@sapphire/framework@*":
    dependencies:
      discord.js: "^13.8.1"
      "@discordjs/builders": "*"
  "@sapphire/plugin-logger@*":
    dependencies:
      "@sapphire/framework": "*"
      discord.js: "^13.8.1"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.8.1.cjs
