version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    environment:
      - DB_URI=mongodb://root:example@mongo:27017/confebot_local?authSource=admin&retryWrites=true&w=majority
      - REDIS_URI=redis://redis:6379
    volumes:
      - .:/home/node/app
      - bot_node_modules:/home/node/app/node_modules
  redis:
    image: 'redis:alpine'
    ports:
      - 8080:6379
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  bot_node_modules:
