name: CI
on: [push, pull_request]

jobs:
  eslint:
    name: Lint and build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Install npm dependencies
      run: npm install
    - name: Run ESLint
      run: npm run lint
    - name: Build TypeScript
      run: npm run build